version: "3.7"

services:

  flask:
    image: teekay2203/myjokes:3.0
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - 8080

  nginx:
    image: teekay2203/mynginx:3.0
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
